### ISSUE TITLE
Fix the documentation

### ISSUE THREAD

**Issue by pattacini** [robotology/funny-things#10]
Hi @alecive 

Could you please give a glance at the documentation?
It seems it doesn't show up correctly in some of the pages.

Thanks!

cc @vtikha

**Comment by alecive** [comment]
Ok so to put things clear:

  * I was able to access the following links:
    * http://robotology.github.io/funny-things/
    * http://robotology.github.io/funny-things/iCubBreather/
    * http://robotology.github.io/funny-things/iCubBlinker/
    * http://robotology.github.io/funny-things/doxygen/doc/html/modules.html (and everything inside the doxygen documentation)
  * I was **NOT** able to access the following links:
    * http://robotology.github.io/funny-things/tags.html
    * http://robotology.github.io/funny-things/modules.html
    * http://robotology.github.io/funny-things/authors.html

Do you confirm? I would like to not have mismatch with your experience.

Also, if this is the case, we should decide what to do with the whole `github page` thing. Specifically: are we going to keep it? Is it any useful in the current state? Are the pages that right now give a 404 worth having?

**Comment by pattacini** [comment]
For the first question: is it all ok.

For the second question, what do you mean? We definitely stick to **GH pages**, though the effort to spread this way of producing documentation is still to be planned.

I'd suggest to keep those pages giving `404` error.

**Comment by alecive** [comment]
Ok, I'll work on it. It is probably due to some changes on jekyll (it was upgraded some months ago).

**Comment by alecive** [comment]
Ok the issues should be fixed. They were do to some major `jekyll` changes that were breaking the API here and there.

I also improved the website in multiple ways, but nothing that should affect the functionality.

Most of these things are difficult to test locally, though. I took a look at the website, and everything seems fine to me, but please report if you experience any other problem. Closing for now.

**Comment by pattacini** [comment]
Working nicely, thanks a lot!

**Comment by pattacini** [comment]
Hey @alecive always remember to squash commits of `gh-pages` branches in order to be in the condition described here: https://github.com/robotology/how-to-document-modules#updating-the-documentation.

I've already done the squashes 😄  ➡️ `git pull --rebase` your local branches!

**Comment by alecive** [comment]
eheh forgot about that :smile: 
On the same topic, is the doxy in need of an update?

**Comment by pattacini** [comment]
Don't think so...
