### ISSUE TITLE
Old yarp lua method names in lua scripts

### ISSUE THREAD

**Issue by xEnVrE** [robotology/funny-things#12]
It seems that scripts in https://github.com/robotology/funny-things/tree/master/app/scripts/lua are using the old lua method names `yarp.Time_delay` and `yarp.Time_now`. In recent versions of yarp, they changed to `yarp.delay` and `yarp.now`.

We should update the scripts accordingly.

**Comment by pattacini** [comment]
Thanks @xEnVrE for pointing them out.
I'm on it.
