### ISSUE TITLE
Integrate the head breather with the motionCUT

### ISSUE THREAD

**Issue by alecive** [robotology/funny-things#2]
It would be nice to have an integration between the breather and whatever optical flow module (e.g. the motionCUT would suffice). The behavior would be a general random movement at the head, and a quick saccade toward the movement detected by the motionCUT whenever there such a movement. There would be the necessity to add also the gazecontroller into the loop.

Eventually, we can create a separate module for this, that stops the breather, gazes there, and re-starts the breather after that. What do you think @pattacini ?

**Comment by pattacini** [comment]
Closing, very old 💡 idea that we won't implement anyway.
