### ISSUE TITLE
Cleanup usage of depreated asDouble method

### ISSUE THREAD

**Issue by traversaro** [robotology/funny-things#24]
The code in https://github.com/robotology/funny-things/blob/fea27dc704c9b37e90d01b91b1bb2f8c0a5d25ff/app/scripts/lua/gaze.lua#L85 will break once https://github.com/robotology/yarp/pull/2833 is merged.

**Comment by pattacini** [comment]
Thanks for reporting 👍🏻 
I can have a look searching for those deprecated methods.
